export const CUSTOM_REPOSITORY_METADATA = 'CUSTOM_REPOSITORY_METADATA';

export const DTO_VALIDATION_OPTIONS = 'DTO_VALIDATION_OPTIONS';

export const CUSTOM_STRING_METADATA_KEY = 'CUSTOM_STRING_METADATA_KEY';
